### ISSUE TITLE
MOD_GRADE vs MOD_AGREED_GRADE (SoMI)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#97] opened 2016-07-15 10:35 UTC
Dear All,

I assume there is a difference between these two, as they co-exist in current "in service" UDD 1.2.4 and are also still in for 1.3?

Many Thanks

Rob

**Comment by arc12** [comment] 2016-07-15 12:23
I suspect this is a documentation bug! (a left-over from before we had actual and agreed)

Also I see that there are some [1] against grades and credits-achieved, which can't be right, since these only get meaningful values once there is a result.

Adam

**Comment by robwynj** [comment] 2016-07-17 13:53
Hi Adam,

Thanks for this. Are we saying that ASSESS_AGREED_GRADE / ASSESS_ACTUAL_GRADE should also be optional (on, or the other, or both?) then (in SoAI) for example?

ASSESSMENT_RESULT in SoAI?

Kind Regards

Rob

**Comment by robwynj** [comment] 2016-07-17 13:54
and same for MOD_AGREED_GRADE (SoMI)?

Worth putting these out there now, as I'm taking real data in and there are issues ie. having to put in "NOGRADE" text when the grade is not known, for example to get around these - as we'll want these entries pushed to the LRW to give early MARKs/ GRADEs indications before MOD_AGREED_GRADE is known for example.

Kind Regards

Rob

**Comment by wilmTap** [comment] 2016-07-18 10:25
So we'll mark MOD_GRADE as deprecated, with a pointer to use MOD_AGREED_GRADE instead.

And the following marked as optional from mandatory:
student_on_a_module_instance
MOD_AGREED_GRADE
MOD_CREDITS_ACHIEVED
student_on_assessment_instance
ASSESS_AGREED_GRADE
ASSESS_ACTUAL_GRADE

I think student_on_a_module_instance.ASSESSMENT_RESULT can probably stay, since it has a code 3 'not known' as a valid value.

I'd also propose changing the wording of the description of student_on_a_module_instance.ASSESS_ACTUAL_GRADE from "The actual grade for the assessment attempt." to "The initial grade given for the assessment attempt." and the descriptions of ASSESS_AGREED_GRADE and ASSESS_AGREED_MARK from "The agreed {grade/mark} for the assessment attempt." to "The {grade/mark} that was confirmed for a student following moderation."

There's a lot more subtlety there (e.g. with peer marking or different second marking approaches), but that's for another day...

**Comment by wilmTap** [comment] 2016-07-18 14:47
Agreed.

**Closed** 2016-08-03 16:08 UTC
Labels: Datamodel change, Student on a Module Instance, Student on Assessment Instance
