### ISSUE TITLE
Need AIM ID - APPROVED (for UDD 1.2)

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#1] opened 2016-01-13 13:02 UTC
We need to add AIM_ID to student.  This is the identifier that Shib provides.

**Comment by robwynj** [comment] 2016-01-14 14:16
Will add this into UDD v1.2

**Comment by robwynj** [comment] 2016-01-28 14:15
Confirmed

**Comment by wilmTap** [comment] 2016-02-08 13:13
Am I right in thinking that AIM_ID is defined as the eduPersonTargetedID attribute as used by the UK federation (http://www.ukfederation.org.uk/library/uploads/Documents/identity-provider-deployment.pdf)? If that's the case, then those IDs are limited to a particular service, which in our case would be the Jisc LRW.

Unless someone indicates otherwise, I'll work up a change patch to that effect for review next Monday.

**Comment by wilmTap** [comment] 2016-02-08 23:53
Note issue #2

**Comment by wilmTap** [comment] 2016-02-10 16:48
Addressed in patch #15 
I've assumed that the ID was not for the Jisc LRW itself, but for any UK Federation service provider, since I'm assuming that the requirement came from analysing existing log file data.

**Closed** 2016-02-17 12:58 UTC
Labels: Student
