### ISSUE TITLE
Constraints on MODULEVLEMAP - Incorrect/ Mod Required (UDD 1.2.x/ UDD 1.3.x)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#205] opened 2017-06-13 08:34 UTC
Further to recent work with one of our HEIs, found that the denotation of constraints for the 2 keys (2 fields as were used for UDD 1.2.x, which are now 3 in UDD 1.3.x obviously!) need to be changed - as the LRW API has allowed duplicate entries in based on those 2 contraints combined (the HEI updated their MOD_VLE_IDs) - therefore  the only constraint should be now on the MOD_INSTANCE_ID field only (contraint removed on VLE_MOD_ID).

https://github.com/jiscdev/analytics-udd/blob/v1.3.0/udd/module_vle_map.md

We need this change in ASAP if possible please, and update the API to enforce.

Kind Regards/ Many Thanks

Rob

**Comment by alanepaull** [comment] 2017-06-13 09:27
Sorry, but I don't understand this fully. Are you saying that an HEI has now got a MOD_INSTANCE_ID that maps to more than 1 MOD_VLE_ID, and that you want this to be permitted? This would result in a single MOD_INSTANCE_ID mapping across to several vle modules?

**Comment by robwynj** [comment] 2017-06-13 09:34
No, the other way round Alan!

Many Thanks

Rob

**Comment by alanepaull** [comment] 2017-06-13 09:43
The current constraint permits only 1 MOD_VLE_ID per MOD_INSTANCE_ID, and only 1 MOD_INSTANCE_ID per MOD_VLE_ID. These constraints should already be enforced in the LRW API.

**Comment by alanepaull** [comment] 2017-06-13 10:13
Proposed change is:

MODULE_VLE_MAP_ID ** delete
MOD_INSTANCE_ID [1] ** primary key
VLE_MOD_ID [1]

Views please.

**Comment by arc12** [comment] 2017-06-13 11:51
This strikes me as a LRW bug. I think it is inappropriate to modify a specification to comply with a bug, ESPECIALLY when there are other parties (i.e. us) depending on the data structure being as specified.

The fundamental question is: what is it which logically defines uniqueness? That is what the spec should embody.

Additionally: I can't see how making the data be unique on MOD_INSTANCE_ID resolves the problem.

This is not to say that I/we think the module vle map approach is "the last word". For example, we have found that, in practice, we also may need to join through to student-module-instance records and match the activity data on student id and vle mod id.

I suggest that we should explore "the HEI updated their MOD_VLE_IDs". Is this an exceptional event or one which is likely to be frequent or regular? Did the IDs change, or was this just a re-load with additions, which the LRW failed to process correctly? ...?

**Comment by michaelwebbjisc** [comment] 2017-06-13 12:50
It's not an LRW bug as that is following the spec.

Adam - can you email me separately the detail of how you are relying on this (with examples hence request for email rather than here). 

We can work round this if necessary (and it's less of an issue with 1.3) but I need to see where institutions have multiple VLE_MOD_ID's per MOD_INSTANCE_ID as we've not come across this in the wild yet.

**Comment by arc12** [comment] 2017-06-13 16:22
Re: "The current constraint permits only 1 MOD_VLE_ID per MOD_INSTANCE_ID, and only 1 MOD_INSTANCE_ID per MOD_VLE_ID."
My reading of the spec is that the composite of both IDs should be unique. This allows multiple associations each way. I see no reason to believe allowing that kind of mapping is anything other than necessary to deal with plausible id mappings.

@michaelwebbjisc detail/examples not quick or easy, Fundamentally, changing the uniqueness constraint invalidates all testing done on the module id mapping. This is precisely the kind of thing that should be change-controlled. It is a breaking change.

I think it IS conceivable that a single UDD entity instance might relate to more than one VLE entity instance. To be lax about this is to cross our fingers and hope that one data instance doesn't break all vle data processing for an institution until some hack is put in place.

If the problem is that data was incorrectly inserted, fix the data, don't break the spec.

**Comment by alanepaull** [comment] 2017-06-13 17:24
@arc12 is correct. I was incorrect in my statement of the constraints above. The composite of both IDs should be unique, which permits both to have multiples, as Adam has stated. Apologies for the misleading statement.

**Comment by michaelwebbjisc** [comment] 2017-06-15 15:39
Looks like I lost my comment on this one as I posted it on a train.

We have a secondary issue, in that that entity relationship diagram gets it wrong in a different way:

https://github.com/jiscdev/analytics-udd/blob/master/diagram.md

This occurs on both 1.2.x and 1.3.x

It has correctly documented that this is a one-to-many relationship, but get the relationship the wrong way round.

I'm happy for a short discussion on this one the call, but this is one that must be corrected I'm afraid.  

We can note on the documentation that the error occurred and has been retrospectively corrected (it needs to be corrected in 1.2.x as well).

I'd like the documentation updated as quickly as possible.  Monday's discussion isn't about whether we make this correction, so can we go ahead and do that please.  If we need to discuss have we handle and live issues caused by this then we can pick up Monday.

We can look at supporting a many-to-many relationship in the future, linked into this discussion:

https://github.com/jiscdev/analytics-udd/issues/77

**Comment by alanepaull** [comment] 2017-06-15 15:45
OK. I'll get on with that now.

**Comment by arc12** [comment] 2017-06-15 15:52
I remain unconvinced that it is a 1:many on logical grounds. Convince me!

Secondly, the 1.2 spec states:
>     MOD_INSTANCE_ID [1] *
>     VLE_MOD_ID [1] *
> 
> * indicates that the property is part of a composite primary key for this entity.

If that is a composite PK then we are in many:many territory, surely!

**Comment by alanepaull** [comment] 2017-06-15 15:59
I can change in the MD files in master, v1.2.7 and all v1.3.x, so that VLE_MOD_ID is not constrained (deleting the *).
The diagram is not straightforward. The current relationship is between module_instance and module_vle_map - currently this is 1 module_instance to many module_vle_map. The removal of the VLE_MOD_ID constraint doesn't make this 1 to many the other way round. The MOD_INSTANCE_ID constraint means that MOD_INSTANCE_ID is unique on both entities, so it's 1:1. The vle_mod is not part of the UDD, so there cannot be a 1:n for that. There can only be 1 module_vle_map record for each module_instance. Unless the diagram is vital, I'll just update the MD files; the diagram can wait until tomorrow.

**Comment by alanepaull** [comment] 2017-06-15 16:06
Further discussion may be needed about the primary key - MOD_INSTANCE_ID being unique makes MODULE_VLE_MAP_ID redundant.

**Comment by alanepaull** [comment] 2017-06-15 16:11
I've removed the constraint from VLE_MOD_ID on master, v1.2.7, v1.3.0, v1.3.1 and v1.4.

I've not yet touched the diagram - but I think that is not urgent. It would be helpful if Mike would confirm that. Also, we'll need to discuss on Monday, I think.

**Comment by arc12** [comment] 2017-06-15 16:24
This should not be changed!

**Comment by michaelwebbjisc** [comment] 2017-06-15 16:27
Ah yes, you are right.  It's 1:1.  It's many to one from the course on the VLE to the module instance.  I guess it's the fact that we are breaking out into xAPI here means it doesn't really fit into an ER diagram.

Technically it's not really necessary at all, it could just be in module_instance.  The practical issue at the time was that institutions typically maintain these mappings in a separate system, so it was easier to get it as a separate file.

We've actually got a similar issue with TUTOR_ID in the student entity.  The student records system holds most of the student entity, but not this value. A number of institutions are struggling to get this data into the that entity, just because the department responsible for it are not part of student records team, and working ETL processes across departmental boundaries are a problem. 

It's possible going forward that we might need to consider separating the internal structure of the UDD from the APIs/Upload files to make it easier for institutions.  But that's for another day.

Adam:  A student logs into a VLE (that's sounding like the start of a very bad joke). They see one vle course per module they are taking. It's just the way it's done.  When they get into the course on the VLE it might be shared with other module instances if they share curriculum, but students don't login to a VLE and see multiple VLE courses for each of the modules they are taking. Are there ever, ever exceptions? Probably, but there are for everyone we do (can a student have more than one student ID? yes, but it's pretty unusual).  Gearing up all the processing of VLE data to cater for a hypothetical situation isn't a good use of time or resources.  We essentially be saying that every service using the UDD would have to factor in catering for a situation that is really, really edge.

**Comment by arc12** [comment] 2017-06-15 18:41
I just checked D&G module vle map

duplicates on MOD_INSTANCE_ID?
Yes 1200 of them

Examples:
> D0SF10^0^A^2014/5^B1^C,int2hair
> D0SF10^0^A^2014/5^B1^C,D0SF10

> DF4Y34^0^A^2014/5^BB^C,DF4Y34
> DF4Y34^0^A^2014/5^BB^C,DF4Y34-ONLINE

**Comment by alanepaull** [comment] 2017-06-20 13:55
Monday 19 June: Discussed at length, but no definitive conclusions. We agreed that Tribal would provide data for problematic examples (Aston, D&G), and Michael would review possible solutions at the data level and in discussion with Rob, Adam, Craig and Alan. The E-R diagram needs extensions to show how the entities linked into xAPI data.

**Comment by robwynj** [comment] 2017-06-30 14:38
Further to this week's meeting between us and Tribal, with D&G - we need to resolve this issue via Michael's suggested approach, to cover FE "module instance" (subject to confirmation of technical feasibility with HT2 next week) - so that the LRW API is able to utilise the modulevlemap to cater for both HE and FE (multiple VLE course IDs) - based on a new field/ flag provided within the INSTITUTION entity.

@michaelwebbjisc feel free to comment further on this / add detail.

**Comment by arc12** [comment] 2017-07-05 13:26
I would be inclined to cast this in terms of additional constraints, as follows:

Starting point is the current constraint = the union of MOD_INSTANCE_ID and VLE_MOD_ID is unique. This is de facto the default in the current data and LRW.

Then we have an additional value on INSTITUTION which captures additional constraints. In this case, we allow for only one additional constraint: that MOD_INSTANCE_ID must be unique by itself. If this is missing, we assume the default.

I think that will help to make the referential logic more clear, hence more robust in implementation. The forumation as currently drafted makes me feel that the cross-listed module scenario isn't properly covered (it would require mode=2 but that is mute about the navigation from UDD MOD to VLE MOD, which is what triggered this whole issue).

**Comment by robwynj** [comment] 2017-07-06 07:34
Agreed.

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk/>

**Comment by alanepaull** [comment] 2017-07-06 10:30
How about this text in module_VLE_map:

"\* indicates that the property has a uniqueness constraint for this entity. The default is that MOD_INSTANCE_ID and VLE_MOD_ID forms a unique constraint. However, for some institutions a single VLE_MOD_ID maps to several MOD_INSTANCE_ID values, in other words an entry in the VLE is cross-listed against several modules in the Student Record System. In this case, the MOD_INSTANCE_ID values in module_VLE_map must be unique, so that several VLE_MOD_ID values map to 1 MOD_INSTANCE_ID value. This additional constraint is implemented through setting the MODULE_VLE_MAP_MODE property in the institution entity to "1"."

Then in the institution.md we adjust it so that MODULE_VLE_MAP_MODE is clearly optional (and repeat much of the above description for clarity).

**Comment by alanepaull** [comment] 2017-07-06 10:33
Comment updated to get the 1 to many the right way round. Apologies to those who read the wrong version prior to correction.

**Comment by alanepaull** [comment] 2017-07-06 10:43
Should the value of the MODULE_VLE_MAP_MODE property be "1", or "true"? It's properly a Boolean, but we've not used Boolean format before, so I think "1" with Int format may be preferable?

**Comment by robwynj** [comment] 2017-07-07 09:48
Can we confirm (ETA) please of when we can "go live" with this fix for UDD, and push to HT2 for LRW / API implementation - @ht2 can you please confirm your thoughts on the above, and let us know if this is all technically possible on the LRW/ API side please.

Many Thanks

Rob

**Comment by alanepaull** [comment] 2017-07-07 10:35
Rob
There are 4 issues outstanding with a v1.3.1 label. Once these have been agreed and implemented, we're good to go. These are #208 (the one you opened on extensions yesterday), #204 and #205 (both these are the module vle map issue), #206 (representing percentages - just for Craig to OK).

I've put the latest re-draft of the module vle map issue solution into v1.3.1. So, we're ready to go with v1.3.1, if everyone agrees with this!

I would strongly recommend some final checking and validation testing, so that we're sure no changes to the release. I'm conscious that the late changes have come from me, and I'm not infallible :).

Alan

**Comment by ht2** [comment] 2017-07-07 11:07
Hi guys,

So @michaelwebbjisc and I had a chat and I think this is what we will do at the DB level.

There will be a new (hidden) key on the table called `UNIQUE_KEY` (with a unique index set across `organisation` and this new key) which will be constructed by the API service as models are sent in. 

The construction of this field will be determined based on the value of the new `MODULE_VLE_MAP_MODE `  on the INSTITUTION schema. So, for every INSTITUTION referenced in each MODULE_VLE_MAP model, we need to retrieve the `mode` for that institution and then construct as either (please correct me if this is in anyway wrong....):

### Mode 0
`MOD_INSTANCE_ID`

### Mode 1
`MOD_INSTANCE_ID`

### Mode 2
`MOD_INSTANCE_ID` + `VLE_MOD_ID`

What we need to avoid doing is pushing any unqiue constraint calculation onto the API server; this is a database issue and it is best served to do this efficiently. It's unfortunate we will have to do the INSTITUTION lookup on insertion of every MODULEVLEMAP, but we can easily cache that data to avoid repeated "n+1" query issues.

As I spelt out to Michael, where this breaks down for me is where the `MODULE_VLE_MAP_MODE` is changed; I can't work out, short of ensuring that all VLEMAPS are flushed how you can realistically ensure consisetnecy of those unique keys if the mode can be changed on the fly by another API request. I would potentially suggest that field is in some way "protected" from updates, with either intervention required at the DB level, or by an additional client scope that would provide that override functionaility. Even then, it would be up to the data provider to flush down the MODULEVLEMAP, or be aware that the data in those models may not conform to the updated MODE on the instutition.

Regarding time frames to implement, this is a fairly involved change for us as up to now all the models just behave with the same logic for I/O. As such @ryansmith94 will need to flesh out a new extended model and request routes for the MODULEVLEMAPs that will have this extra logic. The database schema changes are trivial.

We currently don't have any time "booked in" to handle 1.3.1 changes, but it feels like that is something that needs to happen. From our side time is quite tight, I don't perceieve us having this pushed to the UDD server anytime before August due to other commitments, but that is always up for discussion if priorities are critical and I can take any proposals to Ben (Betts) around resourcing where required.

**Comment by alanepaull** [comment] 2017-07-10 12:38
There was additional discussion here after the Mode = 0, 1 or 2 suggestion. The new suggestion has been documented in v1.3.1 as follows in the module_VLE_map MD file:

<text>

*  [MODULE_VLE_MAP_ID](#module_vle_map_id) **
*  [MOD_INSTANCE_ID](module_instance.md#mod_instance_id) [1] *
*  [VLE_MOD_ID](#vle_mod_id) [1] *

\** indicates that the property is the primary key for this entity; if not provided by data supplier, will be LRW generated.  

\* indicates that the property has a uniqueness constraint for this entity. The default is that MOD_INSTANCE_ID and VLE_MOD_ID forms a unique constraint. However, for some institutions a single VLE_MOD_ID maps to several MOD_INSTANCE_ID values, in other words an entry in the VLE is cross-listed against several modules in the Student Record System. In this case, the MOD_INSTANCE_ID values in module_VLE_map must be unique, so that several MOD_INSTANCE_ID values map to 1 VLE_MOD_ID value. This additional constraint is implemented through setting the MODULE_VLE_MAP_MODE property in the institution entity to "1".

</text>

And in the institution.md as:

<text>

MODULE_VLE_MAP_MODE

Description

This property enables an institution to specify a 1 to many mapping between MOD_INSTANCE_ID and VLE_MOD_ID (see the module_VLE_map entity). By default, MOD_INSTANCE_ID plus VLE_MOD_ID form a unique constraint in module_VLE_map, showing that each module in the VLE maps to 1-and-only-1 module in the Student Record System. In this usual case, MODULE_VLE_MAP_MODE should be omitted from the institution entity.

However, for some institutions a single VLE_MOD_ID maps to several MOD_INSTANCE_ID values, in other words an entry in the VLE is cross-listed against several modules in the Student Record System. In this case, the MOD_INSTANCE_ID values in module_VLE_map must be unique, so that several MOD_INSTANCE_ID values can map to 1 VLE_MOD_ID value. This additional constraint is implemented through setting the MODULE_VLE_MAP_MODE property to "1".

Purpose
To enable the constraints on the module_VLE_map entity to be varied between institutions.

Derivation
Jisc

Valid Values
1

Format
Int

Notes
This property will be either not present, or present and set to "1".

</text>

Does this change @ht2's appreciation? Or are @arc12 and others content to go with the Mode = 0, 1 or 2 suggestion?

**Comment by ht2** [comment] 2017-07-10 12:43
I'm happy for there only to be 2 "modes", but I think the mode should be _able_ to be set to `0`, with a LRW applied default of `0` if not sent. Sending it in as `1` and having the dual constraint if fine with me too.

**Comment by alanepaull** [comment] 2017-07-17 09:56
We have 2 proposals:

**(Proposal 1) MODULE_VLE_MAP_MODE in institution. Mandatory, with values 0, 1 or 2.** 

0 (Default), where 1 MOD_INSTANCE_ID value maps to 1 and only 1 VLE_MOD_ID value.
1, where 1 MOD_INSTANCE_ID value maps to 1 or many VLE_MOD_ID values.
2, where 1 VLE_MOD_ID value maps to 1 or many MOD_INSTANCE_ID values.

**(Proposal 2) MODULE_VLE_MAP_MODE in institution. Optional, value 1 if present.**

If absent, then MOD_INSTANCE_ID plus VLE_MOD_ID form a unique constraint in module_VLE_map, showing that each module in the VLE maps to 1-and-only-1 module in the Student Record System.
If present, value must be set to "1", and MOD_INSTANCE_ID values in module_VLE_map must be unique, so that several MOD_INSTANCE_ID values can map to 1 VLE_MOD_ID value.

We need to decide on which Proposal to implement. I have no recommendation on this, because it depends on implementation details that I don't have enough knowledge about.

**Comment by ht2** [comment] 2017-07-17 10:41
Hey guys, lets put this as a high priority talking point on today's chat (3:30)

**Comment by arc12** [comment] 2017-07-17 11:00
**(Proposal 3) MODULE_VLE_MAP_MODE in institution. Optional, value 0 assumed if absent.**

If absent or "0", then MOD_INSTANCE_ID plus VLE_MOD_ID form a unique constraint in module_VLE_map.
If value "1" then MOD_INSTANCE_ID values in module_VLE_map must be unique

A value of 0 supports a many-to-many relationship between UDD Module Instances and VLE Modules. A value of 1 constrains there to be a single VLE Module for each UDD Module Instance, although cross-listed modules may still have UDD Module Instances referring to the same VLE Module. A value of 1 should be provided if the constraint which it indicates applies.

**Comment by ht2** [comment] 2017-07-17 11:26
@arc12 I've just realised, I have no idea how we're meant to know which institution (`TENANT_ID`) relates to these models in order to check the `MODULE_VLE_MAP_MODE`? Is `TENANT_ID` stored on the related Module or Module Instance?

**Comment by alanepaull** [comment] 2017-07-17 13:51
`TENANT_ID` is not on module or module_instance. Currently the only link between module and institution is via student_on_course_instance.

If `TENANT_ID` isn't likely to be required elsewhere in relation to module or module_instance, this could be resolved by adding in `TENANT_ID` to module_vle_map. If it's likely to be a longer term problem, then it would probably require adding `TENANT_ID` to module. That would be a breaking change, as it would have to be mandatory.

Worth noting that period only links directly to institution. There's no link between module_instance and period except via student_on_course_instance, so I think that looking up `MOD_PERIOD.module_instance` may be problematic.

If these linking bits are genuine issues, then I think we ought to be considering adding `TENANT_ID` to module. However, have there been other methods for getting the period data?

**Comment by ht2** [comment] 2017-07-17 14:56
Going with @arc12's proposal 3:

Unique by:
Value 0: MOD_INSTANCE_ID + VLE_MOD_ID 
Value 1: MOD_INSTANCE_ID + VLE_MOD_ID 

Institution is found via the first in the organisation. If no institution is present, value 0 is assumed

**Comment by alanepaull** [comment] 2017-07-18 08:24
Monday 17 July: as noted by @ht2 above. Plus, there is no issue with tenant_id because in practice the organisation can be identified through hidden data on each entity.

**Comment by alanepaull** [comment] 2017-07-18 08:51
Changes now committed to institution.md and to module_vle_map.md. I would be grateful if someone could double-check them, particularly @arc12 and / or @ht2.

**Comment by arc12** [comment] 2017-07-18 09:13
Re MODULE_VLE_MAP_MODE:

A. I would spell out the terse mode=n => constraint=c

HT2 said
> Value 0: MOD_INSTANCE_ID + VLE_MOD_ID
> Value 1: MOD_INSTANCE_ID

I said:
> If absent or "0", then MOD_INSTANCE_ID plus VLE_MOD_ID form a unique constraint in module_VLE_map.
> If value "1" then MOD_INSTANCE_ID values in module_VLE_map must be unique

B. I think the description confuses.
Cross-listing works in either case of the mode. As I understand the term it refers to modules with different names/ids being taught in the same classes and having the same VLE areas.
The key point about mode=1 is that it requires that there is only ever a single VLE module for a given UDD module instance. Mode 1 would not support a situation where modules share a VLE space in addition to having their own.

**Comment by arc12** [comment] 2017-07-18 09:16
same issue with "cross-listing" in module vle map entity notes

**Comment by alanepaull** [comment] 2017-07-18 09:22
Ok, how about changing the description to this briefer version (not mentioning the term "cross-listing"):

"This property enables an institution to specify the type of relationship between the module_instance in the Student Record System and module information in the VLE, identified by MOD_INSTANCE_ID and VLE_MOD_ID respectively. By default, MOD_INSTANCE_ID plus VLE_MOD_ID form a unique constraint in module_VLE_map, which supports a many-to-many relationship between them.

- If absent or "0", then MOD_INSTANCE_ID plus VLE_MOD_ID form a unique constraint in module_VLE_map.

- If "1", then MOD_INSTANCE_ID values in module_VLE_map must be unique"

This text moved to Notes: "If MODULE_VLE_MAP_MODE is absent, a default value of 0 for this property will be assumed. This property value can be supplied explicitly, if desired." 

And reflect this similarly in module_vle_map.

Is this better?

**Closed** 2017-08-04 12:54 UTC
Labels: fortnightly call, vle map
