### ISSUE TITLE
String (255) should be clear that this is bytes and not characters

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#284] opened 2018-07-04 15:02 UTC
As per subject following a query with Aberystwyth:

> I'm sending max 255 chars, but in this case the strings are 259 bytes due to multi-byte character sets. It's my understanding that UTF8 characters can take up to 3 bytes in typical usage

**Comment by arc12** [comment] 2018-07-09 08:57
I'd always assumed this meant 255 characters, NOT bytes!

**Comment by joshring** [comment] 2018-07-10 13:18
I am also surprised it is bytes

**Comment by gmoger-jisc** [comment] 2018-07-10 13:20
Let me double check this then.

**Comment by alanepaull** [comment] 2018-07-11 11:42
I think that we should be using 255 characters, not bytes. This is to maintain encoding independence in the spec. If we say bytes, then difference encoding systems map to different numbers of characters for the same maximum bytes, and potential nightmare ensues.

**Comment by alanepaull** [comment] 2018-07-18 15:09
16 July 2018 update: @ryansmith94 to investigate.

**Comment by ryansmith94** [comment] 2018-07-25 16:06
So upon looking into this further JSON and JS actually seem to be UTF-16 according to the [utfstring package on NPM](https://www.npmjs.com/package/utfstring) which states the following.

> Javascript strings are encoded in UTF-16, meaning every character takes up 16 bits, or 2 bytes (there are 8 bits per byte). The problem is that not every Unicode character can be encoded in 2 bytes, since 216 is only 65536 - not nearly enough space to represent each of the hundreds of thousands of Unicode characters.
> 
> To mitigate this problem, Javascript (as well as other languages and platforms that use UTF-16 encoding) makes use of what are called "surrogate pairs." Surrogate pairs are two encoded characters that represent a single logical character. Together they are 4 bytes wide and can represent every Unicode character (232 = 4,294,967,296).
> 
> Unfortunately, that's where the good news ends. Javascript still counts each group of two bytes as a character, meaning any character made up of a surrogate pair looks like two logical characters to Javascript instead of just one.

This means that `'𤔣'.length` is evaluated to 2 instead of 1. This is a bit of a problem, but I'm not sure if it's the problem you're actually having. Gareth sent over an example of an Assessment Instance that was failing where `pasioâr` was actually being sent as `pasio\u00c3\u00a2\u00c2\u20ac\u00c2\u2122r`. I've just tried `'â'.length` in JavaScript and it actually evaluated to 1 not 2. Additionally the API accepted that character like that, correctly stored it, and correctly returned the character. So I think this issue can actually be resolved by simply not replacing these characters with escaped unicode.

**Comment by gmoger-jisc** [comment] 2018-07-25 20:09
So this looks to be an issue with how we are handling XML files and reading them as latin-1 instead of UTF-8.  When we import 'pasioâr' as latin-1 it is adding the extra byte/character and evaluating its length as 8.  As utf-8 this does not happen and evaluates to 7.

As we specify UTF-8 for all file submissions I'm not sure why this is being used, unless for some legacy support.  I will need to test switching the encoding to make sure we can still load data for all sites using XML but I suspect it will be fine.

Ryan - thanks for investigating this so thoroughly, we should have picked it up on our side.

This issue can be closed and no update to the specification is required.  To confirm, 255 characters is what we should be allowing for strings and not bytes.

**Comment by ryansmith94** [comment] 2018-07-25 21:54
No worries, @gmoger-jisc thanks for checking this out on your end, hope the switch in encoding goes okay 👍

**Comment by arc12** [comment] 2018-07-26 08:23
A sadly familiar story... I've seen so many cases where somewhere along the way some data transfer got cocked-up character encodings. We ended up using a Python package ftfy to try to intelligently cleanse data that was supposed to be utf-8 but contained byte sequences that are not valid in utf-8.

The earlier in the process we get things clean the better!

I suspect the problem is rooted in lax controls/validation/cleaning of cut/paste data on SRS entry, coupled with widespread confusion over the difference between character codes,  character encoding, and glyphs.

One thing to be ultra-careful about is truncating over-length strings; if this happens in the middle of a surrogate pair, very wierd things can happen in downstream processing.

**Closed** 2018-08-13 14:36 UTC
Labels: fortnightly call
